name: Build and Test

permissions:
  contents: write

on:
  push:
    branches:
      - main

jobs:
  rust-container:
    name: Generate Rust
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: "Install cargo dev"
        run: cargo build --release && mv ./target/release ./npm

      - name: "Run rust-to-npm"
        run: cd ./npm

      - name: Setup pnpm
        uses: pnpm/action-setup@v2
        id: pnpm-install
        with:
          version: 7
          run_install: true
          dest: ./npm

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 18.16
          cache: pnpm

      - name: Release
        env:
          GITHUB_TOKEN: ${{ secrets.PERSONAL_GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: npx semantic-release
